language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
before_install:
  - npm config set loglevel warn
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 1"
script:
  - "psql -c 'create database travis;' -U postgres"
  - "cd db"
  - "npm install"
  - "pg-migrate -d migrations"
  - "npm test"
  - "cd .."
  - "cd api"
  - "npm install"
  - "npm test"
  - "cd .."
  - "cd web"
  - "npm install"
  - "npm test"
  - "cd .."
  - "cd workers"
  - "npm install"
  - "npm test"
  - "cd .."
  - "cd client"
  - "npm install"
  - "npm test"
  - "cd .."
  - "cd margin"
  - "npm install"
  - "npm test"
  - "cd .."
