language: node_js
env:
  - NODE_ENV=travis
before_install:
  - npm config set loglevel warn
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 1"
script:
  - "psql -c 'create database travis;' -U postgres"
  - "pushd db"
  - "npm install"
  - "node ./node_modules/pg-migrate/bin/pg-migrate -d migrations -u postgres://postgres@localhost/travis"
  - "node ./node_modules/pg-test/bin/pg-test"
  - "popd"
