language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
before_install:
  - npm config set loglevel warn
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 1"
script:
  - "psql -c 'create database travis;' -U postgres"
  - "pushd db"
  - "npm install"
  - "pg-migrate -d migrations"
  - "npm test"
  - "popd"
  - "pushd api"
  - "npm install"
  - "npm test"
  - "popd"
  - "pushd web"
  - "npm install"
  - "npm test"
  - "popd"
  - "pushd workers"
  - "npm install"
  - "npm test"
  - "popd"
  - "pushd client"
  - "npm install"
  - "npm test"
  - "popd"
  - "pushd margin"
  - "npm install"
  - "npm test"
  - "popd"
